use super::super::{
    ai_smells, architecture, boundaries, discipline, duplication, framework, hotpath, hotpath_ext,
    maintainability, mlops, observability, packaging, performance, quality, structure,
};
use super::runtime::{
    ai_smells_file_family_findings, ai_smells_function_family_findings,
    architecture_file_family_findings, architecture_function_family_findings,
    boundaries_file_family_findings, boundaries_function_family_findings,
    cross_file_dupe_repo_findings, cross_file_literal_repo_findings,
    deep_inheritance_repo_findings, discipline_function_family_findings,
    duplicate_query_fragment_repo_findings,
    duplicate_transformation_pipeline_repo_findings, duplication_file_family_findings,
    duplication_repo_family_findings, framework_family_findings, hotpath_ext_family_findings,
    hotpath_family_findings, maintainability_family_findings, maintainability_file_family_findings,
    mlops_family_findings, observability_file_family_findings, observability_function_family_findings,
    performance_family_findings, structure_file_family_findings,
    structure_function_family_findings, structure_repo_family_findings,
    test_utility_logic_repo_findings,
};
use super::types::{
    FileEvaluator, FunctionEvaluator, PythonFileRuleSpec, PythonFunctionRuleSpec,
    PythonRepoRuleSpec, RepoEvaluator,
};

const QUALITY_FUNCTION_RULE_IDS: &[&str] = &[
    "async_lock_held_across_await",
    "async_retry_sleep_without_backoff",
    "background_task_exception_unobserved",
    "dataclass_heavy_post_init",
    "mutable_default_argument",
    "pickle_deserialization_boundary",
    "public_any_type_leak",
    "subprocess_shell_true",
    "tar_extractall_unfiltered",
    "tempfile_without_cleanup",
    "typeddict_unchecked_access",
    "unsafe_yaml_loader",
    "untracked_asyncio_task",
];

const PERFORMANCE_FUNCTION_RULE_IDS: &[&str] = &[
    "blocking_sync_io_in_async",
    "deque_candidate_queue",
    "full_dataset_load",
    "list_materialization_first_element",
    "list_membership_in_loop",
    "recursive_traversal_risk",
    "repeated_len_in_loop",
    "string_concat_in_loop",
    "temporary_collection_in_loop",
];

const MAINTAINABILITY_FUNCTION_RULE_IDS: &[&str] = &[
    "broad_exception_handler",
    "builtin_reduction_candidate",
    "environment_boundary_without_fallback",
    "eval_exec_usage",
    "exception_swallowed",
    "external_input_without_validation",
    "hardcoded_business_rule",
    "hardcoded_path_string",
    "magic_value_branching",
    "missing_context_manager",
    "network_boundary_without_timeout",
    "none_comparison",
    "print_debugging_leftover",
    "public_api_missing_type_hints",
    "redundant_return_none",
    "reinvented_utility",
    "side_effect_comprehension",
    "variadic_public_api",
];

const STRUCTURE_FUNCTION_RULE_IDS: &[&str] = &[
    "god_function",
    "mixed_concerns_function",
    "name_responsibility_mismatch",
];

const AI_SMELLS_FUNCTION_RULE_IDS: &[&str] = &["textbook_docstring_small_helper"];

const HOTPATH_FUNCTION_RULE_IDS: &[&str] = &[
    "csv_writer_flush_per_row",
    "dict_items_or_keys_materialized_in_loop",
    "enumerate_on_range_len",
    "in_check_on_list_literal",
    "json_loads_same_payload_multiple_times",
    "list_comprehension_only_for_length",
    "read_then_splitlines",
    "readlines_then_iterate",
    "regex_compile_in_hot_path",
    "repeated_json_dumps_same_object",
    "repeated_open_same_file_in_function",
    "sorted_only_for_first_element",
    "string_startswith_endswith_chain",
    "write_without_buffering_in_loop",
];

const HOTPATH_EXT_FUNCTION_RULE_IDS: &[&str] = &[
    "append_then_sort_each_iteration",
    "concatenation_in_comprehension_body",
    "dict_copy_in_loop_same_source",
    "filter_then_count_then_iterate",
    "gzip_open_per_chunk",
    "json_encoder_recreated_per_item",
    "list_copy_in_loop_same_source",
    "nested_list_search_map_candidate",
    "path_resolve_or_expanduser_in_loop",
    "pickle_dumps_in_loop_same_structure",
    "repeated_datetime_strptime_same_format",
    "repeated_dict_get_same_key_no_cache",
    "repeated_hashlib_new_same_algorithm",
    "repeated_isinstance_chain_same_object",
    "repeated_list_index_lookup",
    "repeated_locale_or_codec_lookup_in_loop",
    "repeated_string_format_invariant_template",
    "set_created_per_iteration_same_elements",
    "sort_then_first_or_membership_only",
    "string_join_without_generator",
    "tuple_unpacking_in_tight_loop",
    "urlparse_in_loop_on_invariant_base",
    "xml_parse_same_payload_multiple_times",
    "yaml_load_same_payload_multiple_times",
];

const FRAMEWORK_FUNCTION_RULE_IDS: &[&str] = &[
    "celery_delay_in_loop_without_canvas",
    "celery_result_get_inside_task",
    "celery_task_reads_env_per_invocation",
    "click_typer_config_file_loaded_per_command",
    "click_typer_env_lookup_per_command",
    "click_typer_http_client_created_per_command",
    "django_all_without_limit_in_view",
    "django_create_single_in_loop",
    "django_delete_single_in_loop",
    "django_migration_code_in_view",
    "django_n_plus_one_no_select_related",
    "django_queryset_count_then_exists",
    "django_queryset_evaluated_multiple_times",
    "django_queryset_len_instead_of_count",
    "django_queryset_order_by_random",
    "django_raw_sql_in_loop",
    "django_save_full_model_in_loop",
    "django_update_single_in_loop",
    "django_values_vs_full_model_in_loop",
    "fastapi_background_task_exception_silent",
    "fastapi_dependency_creates_client_per_request",
    "fastapi_response_model_without_orm_mode",
    "fastapi_sync_def_with_blocking_io",
    "flask_app_config_read_per_request",
    "flask_debug_mode_in_production_code",
    "flask_file_read_per_request",
    "flask_global_db_connection_per_request",
    "flask_json_encoder_per_request",
    "flask_no_streaming_for_large_response",
    "flask_request_body_parsed_multiple_times",
    "flask_template_rendered_from_string_in_view",
    "large_dict_literal_response_in_handler",
    "middleware_compiles_regex_per_request",
    "middleware_creates_http_client_per_request",
    "middleware_loads_config_file_per_request",
    "pydantic_model_dump_then_json_dumps",
    "pydantic_model_validate_after_json_loads",
    "response_json_dumps_then_response_object",
    "sqlalchemy_commit_per_row_in_loop",
    "sqlalchemy_create_engine_per_request",
    "sqlalchemy_expire_on_commit_default_in_async",
    "sqlalchemy_n_plus_one_lazy_load",
    "sqlalchemy_query_in_loop",
    "sqlalchemy_session_not_closed",
    "sqlmodel_commit_per_row_in_loop",
    "sqlmodel_session_exec_in_loop",
    "sqlmodel_unbounded_select_in_handler",
    "template_render_in_loop",
    "upstream_call_without_timeout_in_handler",
    "upstream_http_call_per_item_in_handler",
    "upstream_response_not_checked_before_decode",
];

const MLOPS_FUNCTION_RULE_IDS: &[&str] = &[
    "data_pipeline_no_error_handling",
    "dataset_not_using_dataloader",
    "embedding_computed_per_request",
    "embedding_dimension_mismatch_silent",
    "entire_dataframe_copied_for_transform",
    "global_state_in_data_pipeline",
    "gpu_memory_not_cleared_between_experiments",
    "hardcoded_api_key_in_source",
    "intermediate_dataframe_not_freed",
    "langchain_chain_built_per_request",
    "llm_api_call_in_loop_without_batching",
    "llm_full_response_loaded_into_memory",
    "llm_response_not_cached_same_input",
    "model_eval_mode_missing",
    "model_loaded_per_request",
    "model_to_device_in_loop",
    "no_schema_validation_on_external_data",
    "numpy_append_in_loop",
    "numpy_dtype_mismatch_implicit_cast",
    "numpy_python_loop_over_array",
    "numpy_tolist_in_hot_path",
    "numpy_vstack_hstack_in_loop",
    "pandas_apply_with_simple_vectorizable_op",
    "pandas_chain_assignment_warning",
    "pandas_concat_in_loop",
    "pandas_copy_in_loop",
    "pandas_eval_string_manipulation",
    "pandas_full_dataframe_print_in_production",
    "pandas_inplace_false_reassignment_missing",
    "pandas_iterrows_in_loop",
    "pandas_merge_without_validation",
    "pandas_read_csv_without_dtypes",
    "pandas_read_without_chunksize_large_file",
    "pandas_to_dict_records_in_loop",
    "print_metrics_instead_of_logging",
    "prompt_template_string_concat_in_loop",
    "random_seed_not_set",
    "retry_on_rate_limit_without_backoff",
    "token_count_not_checked_before_api_call",
    "tokenizer_encode_in_loop_without_cache",
    "tokenizer_loaded_per_request",
    "torch_no_grad_missing_in_inference",
    "training_loop_without_zero_grad",
    "vector_store_client_created_per_request",
    "wandb_mlflow_log_in_tight_loop",
];

const PACKAGING_FUNCTION_RULE_IDS: &[&str] = &["python_public_api_any_contract"];

const QUALITY_FILE_RULE_IDS: &[&str] = &[
    "dataclass_mutable_default",
    "import_time_config_load",
    "import_time_file_io",
    "import_time_network_call",
    "import_time_subprocess",
    "module_singleton_client_side_effect",
    "mutable_module_global_state",
    "option_bag_model",
    "public_any_type_leak",
];

const STRUCTURE_FILE_RULE_IDS: &[&str] = &[
    "eager_constructor_collaborators",
    "god_class",
    "monolithic_init_module",
    "monolithic_module",
    "name_responsibility_mismatch",
    "over_abstracted_wrapper",
    "too_many_instance_attributes",
];

const AI_SMELLS_FILE_RULE_IDS: &[&str] = &[
    "enthusiastic_commentary",
    "mixed_naming_conventions",
    "obvious_commentary",
    "unrelated_heavy_import",
];

const MAINTAINABILITY_FILE_RULE_IDS: &[&str] = &["commented_out_code", "mixed_sync_async_module"];

const DUPLICATION_FILE_RULE_IDS: &[&str] = &[
    "duplicate_error_handler_block",
    "duplicate_validation_pipeline",
    "repeated_string_literal",
];

const STRUCTURE_REPO_RULE_IDS: &[&str] = &["deep_inheritance_hierarchy", "tight_module_coupling"];

const DUPLICATION_REPO_RULE_IDS: &[&str] = &[
    "cross_file_copy_paste_function",
    "cross_file_repeated_literal",
    "duplicate_query_fragment",
    "duplicate_test_utility_logic",
    "duplicate_transformation_pipeline",
];

const PACKAGING_REPO_RULE_IDS: &[&str] = &[
    "cross_package_internal_import",
    "pyproject_missing_requires_python",
    "pyproject_script_entrypoint_unresolved",
];

const ARCHITECTURE_FUNCTION_RULE_IDS: &[&str] = &[
    "service_method_accepts_http_request_object",
    "repository_returns_unexecuted_orm_query",
    "view_or_handler_constructs_orm_query_directly",
    "domain_model_class_imports_http_library",
    "service_raises_or_catches_http_exception_type",
    "handler_or_view_builds_raw_sql",
    "service_method_returns_http_response_object",
    "handler_or_view_owns_transaction_lifecycle",
    "service_reads_settings_inline_instead_of_injected",
    "view_or_handler_performs_direct_file_system_io",
    "business_logic_inside_middleware",
    "dependency_injection_bypassed_via_global_singleton",
    "auth_extraction_duplicated_across_views",
    "background_job_depends_on_request_context_object",
    "repository_method_accepts_pydantic_request_schema",
    "celery_or_rq_task_imports_web_framework_app",
    "persistent_model_field_encodes_transport_concern",
    "orm_model_mixes_domain_logic_and_persistence_mapping",
    "validation_rules_duplicated_at_dto_and_domain_layer",
    "asyncio_gather_without_return_exceptions_on_partial_failure_path",
    "thread_local_storage_read_from_async_function",
    "loop_run_until_complete_inside_running_loop",
    "asyncio_sleep_zero_busy_wait_pattern",
    "threading_thread_without_daemon_true_in_server_code",
    "shared_mutable_collection_mutated_across_threads_without_lock",
    "multiprocessing_pool_created_without_context_manager_or_terminate",
    "concurrent_futures_executor_not_shut_down",
    "threading_lock_acquired_blocking_inside_async_def",
    "asyncio_queue_created_without_maxsize_in_producer_path",
    "coroutine_result_discarded_without_await",
    "sync_function_called_from_async_without_executor",
    "untracked_create_task_result_may_hide_exception",
    "semaphore_acquired_without_async_with_context_manager",
];

const ARCHITECTURE_FILE_RULE_IDS: &[&str] = &["asyncio_get_event_loop_at_module_scope"];

const DISCIPLINE_FUNCTION_RULE_IDS: &[&str] = &[
    "exception_raised_without_chaining_original_cause",
    "exception_handler_branches_on_error_message_string",
    "bare_except_clause_catches_system_exit",
    "exception_logged_and_then_re_raised_redundantly",
    "validation_or_parse_error_mapped_to_500_status",
    "exception_silenced_in_cleanup_or_finally_block",
    "project_exception_class_not_inheriting_shared_base",
    "exception_raised_and_caught_for_control_flow_within_same_function",
    "error_message_embeds_sensitive_data",
    "retry_loop_catches_broad_base_exception",
    "transaction_block_missing_rollback_on_exception",
    "assert_used_for_runtime_input_validation_in_production",
    "warning_issued_instead_of_exception_for_invalid_state",
    "exception_handler_returns_default_without_any_logging",
    "deeply_nested_try_except_beyond_two_levels",
    "contextlib_suppress_applied_with_exception_base_class",
    "oserror_caught_without_errno_inspection",
    "custom_exception_encodes_identity_as_string_code_attribute",
    "generator_close_exception_not_handled_when_cleanup_required",
    "overloaded_dispatch_without_typing_overload_decorator",
    "protocol_used_in_isinstance_without_runtime_checkable",
    "optional_parameter_used_without_none_guard",
    "callable_annotation_without_parameter_types",
    "cast_applied_without_preceding_type_narrowing_guard",
    "type_alias_shadows_builtin_name",
    "namedtuple_used_where_dataclass_better_fits",
    "public_function_return_type_annotated_as_union_of_many_unrelated_types",
    "typevar_defined_without_bound_or_constraints_for_narrow_use",
    "generic_class_used_without_type_parameter_application",
    "protocol_method_lacks_type_annotations",
    "typed_dict_key_access_without_get_or_guard",
    "typed_dict_total_false_without_docstring_noting_optional_keys",
    "string_forward_reference_in_annotation_not_under_type_checking_guard",
    "test_function_stacks_too_many_mock_patch_decorators",
    "test_calls_time_sleep_for_coordination",
    "test_mutates_module_global_without_restore",
    "test_asserts_private_attribute_value_instead_of_behavior",
    "test_fixture_calls_datetime_now_without_freezing",
    "test_wraps_sut_in_try_except_hiding_exception_detail",
    "pytest_parametrize_with_single_test_case",
    "test_skipped_with_no_reason_string",
    "test_compares_float_with_equality_operator",
    "test_loads_real_application_config_or_secrets",
    "test_makes_real_outbound_http_call_without_mock_or_vcr",
    "test_function_covers_multiple_unrelated_scenarios",
    "integration_test_writes_state_without_cleanup",
    "pytest_raises_without_match_parameter_on_broad_exception",
    "test_re_implements_production_validation_logic",
    "test_imports_private_production_module",
    "mock_return_value_is_incompatible_type_with_real_signature",
    "unittest_test_class_duplicates_setup_without_base_class",
    "test_depends_on_sibling_test_side_effects",
];

const BOUNDARIES_FUNCTION_RULE_IDS: &[&str] = &[
    "sql_query_built_with_string_formatting_instead_of_parameters",
    "file_path_from_user_input_without_normalization_or_anchor_check",
    "xml_parsing_with_external_dtd_or_entity_processing_enabled",
    "http_client_url_built_from_user_input_without_allowlist",
    "subprocess_invoked_with_shell_true_and_user_derived_input",
    "jinja2_environment_created_with_autoescape_disabled",
    "jwt_decode_allows_none_algorithm_or_no_algorithm_restriction",
    "insecure_hash_algorithm_used_for_security_sensitive_purpose",
    "deserialization_from_external_or_user_controlled_source_with_pickle",
    "debug_or_admin_endpoint_registered_without_environment_guard",
    "weak_random_function_used_for_security_token_generation",
    "open_redirect_via_user_supplied_url_without_allowlist",
    "arbitrary_file_write_via_user_controlled_path",
    "cors_allow_all_origins_set_without_production_environment_check",
    "server_side_template_injection_via_user_input_in_template_source",
    "regex_pattern_with_catastrophic_backtracking_applied_to_unbounded_input",
    "ldap_search_filter_built_from_user_input_without_escaping",
    "state_changing_endpoint_missing_csrf_protection",
    "unbounded_list_accumulation_inside_long_running_function",
    "generator_consumed_twice_without_recreation",
    "file_object_returned_or_stored_without_clear_close_path",
    "weakref_dereferenced_without_live_check",
    "functools_lru_cache_applied_to_instance_method",
    "subprocess_pipe_without_communicate_for_large_output",
    "socket_opened_without_context_manager_or_guaranteed_close",
    "repeated_deepcopy_in_loop_on_same_source_object",
    "redis_commands_issued_individually_in_loop_without_pipeline",
    "unclosed_tempfile_or_tmp_directory_from_tempfile_module",
    "db_connection_pool_size_exceeds_server_max_connections",
    "closure_captures_large_object_after_producing_function_returns",
    "object_allocated_in_tight_loop_expected_to_be_pooled",
    "pydantic_settings_model_allows_post_init_mutation",
    "secrets_manager_client_created_per_function_call",
    "toml_or_ini_config_file_parsed_on_request_path",
    "startup_log_statement_includes_raw_secret_value",
    "pydantic_settings_model_does_not_forbid_extra_fields",
    "yaml_config_loaded_without_safe_loader",
    "application_config_values_validated_lazily_on_first_use",
    "sensitive_config_key_included_in_debug_level_log_dict_dump",
    "multiple_config_sources_merged_without_documented_precedence_order",
    "pydantic_settings_model_missing_env_prefix_isolation",
];

const BOUNDARIES_FILE_RULE_IDS: &[&str] = &[
    "cryptographic_secret_hardcoded_in_test_fixture_or_seed",
    "dotenv_load_dotenv_called_from_multiple_modules",
    "feature_flag_checked_via_inline_env_lookup_across_handlers",
];

const OBSERVABILITY_FUNCTION_RULE_IDS: &[&str] = &[
    "f_string_evaluated_eagerly_inside_logging_call",
    "logger_error_inside_except_without_exc_info",
    "distributed_trace_span_created_without_parent_context_propagation",
    "health_check_handler_queries_slow_database_table",
    "exception_swallowed_before_sentry_or_error_tracker_capture",
    "high_frequency_code_path_logs_without_sampling_or_rate_limit",
    "opentelemetry_span_attribute_attaches_pii_fields",
    "structured_log_record_missing_trace_or_correlation_id",
    "logging_call_inside_signal_handler_function",
    "alert_or_slo_threshold_hardcoded_inside_application_logic",
    "prometheus_or_statsd_metric_emitted_inside_db_result_loop",
    "observability_metric_names_use_inconsistent_separators",
    "star_import_used_in_non_init_production_module",
    "importlib_import_module_called_inside_request_handler",
    "optional_library_import_checked_on_hot_code_path",
    "dynamic_plugin_loaded_from_config_without_registry_allowlist",
    "importlib_metadata_version_queried_inside_request_loop",
    "pkg_resources_used_for_runtime_version_lookup",
    "relative_import_crossing_sibling_package_boundary",
    "sorted_full_collection_to_extract_top_n_elements",
    "linear_membership_test_in_loop_over_large_static_list",
    "manual_dict_increment_instead_of_counter_or_defaultdict",
    "list_pop_zero_used_as_queue_operation",
    "zip_range_len_used_instead_of_enumerate",
    "defaultdict_created_with_lambda_instead_of_builtin_factory",
    "filter_and_map_results_materialized_to_list_at_each_step",
    "frozenset_not_used_for_constant_membership_set_rebuilt_per_call",
    "sorted_list_maintained_with_insert_instead_of_bisect_insort",
    "namedtuple_fields_accessed_by_integer_index",
    "counter_most_common_all_items_retrieved_for_top_one",
    "repeated_key_hash_via_dict_lookup_in_tight_loop",
    "chain_of_boolean_or_conditions_over_same_value_not_using_in_operator",
    "ordered_dict_used_in_python_37_plus_where_dict_suffices",
    "api_endpoint_returns_json_without_documented_response_schema",
    "cursor_based_pagination_missing_stable_sort_tiebreaker",
    "bulk_endpoint_partial_failure_contract_ambiguous",
    "rate_limit_429_response_missing_retry_after_header_or_stable_body",
    "pydantic_validation_error_detail_forwarded_with_internal_field_aliases",
    "state_changing_endpoint_returns_200_with_empty_body",
    "binary_or_multipart_response_missing_explicit_content_type",
    "large_response_body_fully_buffered_in_memory_before_send",
    "api_versioning_in_url_without_matching_router_group",
    "response_envelope_shape_inconsistent_across_siblings_in_same_router",
];

const OBSERVABILITY_FILE_RULE_IDS: &[&str] = &[
    "logging_basic_config_called_from_library_package",
    "logging_set_level_hardcoded_at_module_scope",
    "module_level_side_effect_outside_main_guard",
    "test_support_helpers_located_inside_production_package",
    "init_file_re_exports_private_module_symbols",
    "public_package_missing_all_list",
];

pub(crate) const FUNCTION_RULE_SPECS: &[PythonFunctionRuleSpec] = &[
    PythonFunctionRuleSpec {
        family: "quality",
        rule_ids: QUALITY_FUNCTION_RULE_IDS,
        evaluate: quality::quality_function_findings,
    },
    PythonFunctionRuleSpec {
        family: "performance",
        rule_ids: PERFORMANCE_FUNCTION_RULE_IDS,
        evaluate: performance_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "maintainability",
        rule_ids: MAINTAINABILITY_FUNCTION_RULE_IDS,
        evaluate: maintainability_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "structure",
        rule_ids: STRUCTURE_FUNCTION_RULE_IDS,
        evaluate: structure_function_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "ai_smells",
        rule_ids: AI_SMELLS_FUNCTION_RULE_IDS,
        evaluate: ai_smells_function_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "hot_path",
        rule_ids: HOTPATH_FUNCTION_RULE_IDS,
        evaluate: hotpath_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "hot_path_ext",
        rule_ids: HOTPATH_EXT_FUNCTION_RULE_IDS,
        evaluate: hotpath_ext_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "framework",
        rule_ids: FRAMEWORK_FUNCTION_RULE_IDS,
        evaluate: framework_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "mlops",
        rule_ids: MLOPS_FUNCTION_RULE_IDS,
        evaluate: mlops_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "packaging",
        rule_ids: PACKAGING_FUNCTION_RULE_IDS,
        evaluate: packaging::public_api_any_contract_findings,
    },
    PythonFunctionRuleSpec {
        family: "architecture",
        rule_ids: ARCHITECTURE_FUNCTION_RULE_IDS,
        evaluate: architecture_function_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "discipline",
        rule_ids: DISCIPLINE_FUNCTION_RULE_IDS,
        evaluate: discipline_function_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "boundaries",
        rule_ids: BOUNDARIES_FUNCTION_RULE_IDS,
        evaluate: boundaries_function_family_findings,
    },
    PythonFunctionRuleSpec {
        family: "observability",
        rule_ids: OBSERVABILITY_FUNCTION_RULE_IDS,
        evaluate: observability_function_family_findings,
    },
];

pub(crate) const FILE_RULE_SPECS: &[PythonFileRuleSpec] = &[
    PythonFileRuleSpec {
        family: "quality",
        rule_ids: QUALITY_FILE_RULE_IDS,
        evaluate: quality::quality_file_findings,
    },
    PythonFileRuleSpec {
        family: "structure",
        rule_ids: STRUCTURE_FILE_RULE_IDS,
        evaluate: structure_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "ai_smells",
        rule_ids: AI_SMELLS_FILE_RULE_IDS,
        evaluate: ai_smells_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "maintainability",
        rule_ids: MAINTAINABILITY_FILE_RULE_IDS,
        evaluate: maintainability_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "duplication",
        rule_ids: DUPLICATION_FILE_RULE_IDS,
        evaluate: duplication_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "architecture",
        rule_ids: ARCHITECTURE_FILE_RULE_IDS,
        evaluate: architecture_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "boundaries",
        rule_ids: BOUNDARIES_FILE_RULE_IDS,
        evaluate: boundaries_file_family_findings,
    },
    PythonFileRuleSpec {
        family: "observability",
        rule_ids: OBSERVABILITY_FILE_RULE_IDS,
        evaluate: observability_file_family_findings,
    },
];

pub(crate) const REPO_RULE_SPECS: &[PythonRepoRuleSpec] = &[
    PythonRepoRuleSpec {
        family: "structure",
        rule_ids: STRUCTURE_REPO_RULE_IDS,
        evaluate: structure_repo_family_findings,
    },
    PythonRepoRuleSpec {
        family: "duplication",
        rule_ids: DUPLICATION_REPO_RULE_IDS,
        evaluate: duplication_repo_family_findings,
    },
    PythonRepoRuleSpec {
        family: "packaging",
        rule_ids: PACKAGING_REPO_RULE_IDS,
        evaluate: packaging::pyproject_repo_findings,
    },
];

pub(crate) const PERFORMANCE_EVALUATORS: &[FunctionEvaluator] = &[
    performance::string_concat_findings,
    performance::blocking_sync_io_findings,
    performance::full_dataset_load_findings,
    performance::list_materialization_findings,
    performance::deque_candidate_findings,
    performance::temp_collection_findings,
    performance::recursive_traversal_findings,
    performance::list_membership_findings,
    performance::repeated_len_findings,
];

pub(crate) const MAINTAINABILITY_EVALUATORS: &[FunctionEvaluator] = &[
    maintainability::exception_swallowed_findings,
    maintainability::broad_exception_handler_findings,
    maintainability::eval_exec_findings,
    maintainability::print_debugging_findings,
    maintainability::none_comparison_findings,
    maintainability::side_effect_comprehension_findings,
    maintainability::redundant_return_none_findings,
    maintainability::hardcoded_path_findings,
    maintainability::hardcoded_business_rule_findings,
    maintainability::magic_value_branching_findings,
    maintainability::reinvented_utility_findings,
    maintainability::builtin_reduction_findings,
    maintainability::missing_context_manager_findings,
    maintainability::network_timeout_findings,
    maintainability::env_fallback_findings,
    maintainability::input_validation_findings,
    maintainability::api_type_hint_findings,
    maintainability::variadic_public_api_findings,
];

pub(crate) const STRUCTURE_FUNCTION_EVALUATORS: &[FunctionEvaluator] = &[
    structure::god_function_findings,
    structure::mixed_concern_findings,
    structure::name_responsibility_mismatch_findings,
];

pub(crate) const HOTPATH_EVALUATORS: &[FunctionEvaluator] = &[
    hotpath::regex_compile_in_hotpath_findings,
    hotpath::json_repeated_call_findings,
    hotpath::sorted_first_findings,
    hotpath::len_comprehension_findings,
    hotpath::readlines_then_iterate_findings,
    hotpath::read_splitlines_findings,
    hotpath::in_list_literal_findings,
    hotpath::startswith_chain_findings,
    hotpath::enumerate_range_len_findings,
    hotpath::csv_flush_per_row_findings,
    hotpath::write_in_loop_findings,
    hotpath::repeated_open_findings,
    hotpath::dict_materialization_in_loop_findings,
];

pub(crate) const HOTPATH_EXT_EVALUATORS: &[FunctionEvaluator] = &[
    hotpath_ext::yaml_repeated_load_findings,
    hotpath_ext::xml_repeated_parse_findings,
    hotpath_ext::datetime_strptime_repeated_findings,
    hotpath_ext::hashlib_repeated_findings,
    hotpath_ext::copy_in_loop_findings,
    hotpath_ext::invariant_call_in_loop_findings,
    hotpath_ext::index_in_loop_findings,
    hotpath_ext::append_sort_in_loop_findings,
    hotpath_ext::join_list_comp_findings,
    hotpath_ext::repeated_subscript_findings,
    hotpath_ext::nested_list_search_findings,
    hotpath_ext::sort_then_first_findings,
    hotpath_ext::filter_count_iterate_findings,
    hotpath_ext::repeated_format_findings,
    hotpath_ext::json_encoder_recreated_findings,
    hotpath_ext::gzip_open_per_chunk_findings,
    hotpath_ext::pickle_in_loop_findings,
    hotpath_ext::isinstance_chain_findings,
    hotpath_ext::concat_in_comprehension_findings,
    hotpath_ext::tuple_unpacking_in_tight_loop_findings,
];

pub(crate) const FRAMEWORK_EVALUATORS: &[FunctionEvaluator] = &[
    framework::celery_task_findings,
    framework::click_typer_command_findings,
    framework::django_queryset_findings,
    framework::django_n_plus_one_findings,
    framework::django_loop_db_findings,
    framework::django_values_findings,
    framework::flask_handler_findings,
    framework::fastapi_handler_findings,
    framework::sqlalchemy_findings,
    framework::sqlmodel_findings,
    framework::pydantic_v2_findings,
    framework::middleware_findings,
    framework::handler_fanout_findings,
    framework::template_response_findings,
    framework::django_extra_findings,
    framework::response_extra_findings,
];

pub(crate) const MLOPS_EVALUATORS: &[FunctionEvaluator] = &[
    mlops::pandas_findings,
    mlops::numpy_findings,
    mlops::model_inference_findings,
    mlops::llm_findings,
    mlops::data_pipeline_findings,
    mlops::mlops_extra_findings,
];

pub(crate) const STRUCTURE_FILE_EVALUATORS: &[FileEvaluator] = &[
    structure::monolithic_init_module_findings,
    structure::monolithic_module_findings,
    structure::too_many_attributes_findings,
    structure::god_class_findings,
    structure::eager_constructor_collaborator_findings,
    structure::over_abstracted_wrapper_findings,
    structure::module_name_mismatch_findings,
];

pub(crate) const AI_SMELLS_FILE_EVALUATORS: &[FileEvaluator] = &[
    ai_smells::mixed_naming_convention_findings,
    ai_smells::unrelated_heavy_import_findings,
    ai_smells::obvious_commentary_findings,
    ai_smells::enthusiastic_commentary_findings,
];

pub(crate) const MAINTAINABILITY_FILE_EVALUATORS: &[FileEvaluator] = &[
    maintainability::commented_out_code_findings,
    maintainability::sync_async_module_findings,
];

pub(crate) const DUPLICATION_FILE_EVALUATORS: &[FileEvaluator] = &[
    duplication::repeated_string_literal_findings,
    duplication::repeated_exception_block_findings,
    duplication::repeated_validation_pipeline_findings,
];

pub(crate) const STRUCTURE_REPO_EVALUATORS: &[RepoEvaluator] = &[
    deep_inheritance_repo_findings,
    structure::tight_module_coupling_findings,
];

pub(crate) const DUPLICATION_REPO_EVALUATORS: &[RepoEvaluator] = &[
    cross_file_dupe_repo_findings,
    test_utility_logic_repo_findings,
    cross_file_literal_repo_findings,
    duplicate_query_fragment_repo_findings,
    duplicate_transformation_pipeline_repo_findings,
];

pub(crate) const ARCHITECTURE_EVALUATORS: &[FunctionEvaluator] = &[
    architecture::service_accepts_http_request_findings,
    architecture::repository_returns_query_findings,
    architecture::view_builds_orm_query_findings,
    architecture::domain_imports_http_findings,
    architecture::service_raises_http_exception_findings,
    architecture::handler_builds_raw_sql_findings,
    architecture::service_returns_http_response_findings,
    architecture::handler_owns_transaction_findings,
    architecture::service_reads_settings_inline_findings,
    architecture::handler_direct_file_io_findings,
    architecture::business_logic_in_middleware_findings,
    architecture::di_bypassed_singleton_findings,
    architecture::auth_duplicated_across_views_findings,
    architecture::background_job_uses_request_context_findings,
    architecture::repository_accepts_pydantic_schema_findings,
    architecture::celery_task_imports_web_app_findings,
    architecture::persistent_model_transport_field_findings,
    architecture::orm_model_mixes_logic_findings,
    architecture::validation_duplicated_dto_domain_findings,
    architecture::gather_without_return_exceptions_findings,
    architecture::thread_local_in_async_findings,
    architecture::run_until_complete_in_running_loop_findings,
    architecture::sleep_zero_busy_wait_findings,
    architecture::non_daemon_thread_in_server_findings,
    architecture::shared_mutable_mutated_across_threads_findings,
    architecture::multiprocessing_pool_not_closed_findings,
    architecture::executor_not_shut_down_findings,
    architecture::blocking_lock_in_async_findings,
    architecture::asyncio_queue_no_maxsize_findings,
    architecture::coroutine_result_discarded_findings,
    architecture::sync_called_from_async_without_executor_findings,
    architecture::untracked_create_task_findings,
    architecture::semaphore_without_async_with_findings,
];

pub(crate) const ARCHITECTURE_FILE_EVALUATORS: &[FileEvaluator] = &[
    architecture::event_loop_at_module_scope_file_findings,
];

pub(crate) const DISCIPLINE_EVALUATORS: &[FunctionEvaluator] = &[
    discipline::exception_raised_without_chaining_findings,
    discipline::exception_branches_on_message_findings,
    discipline::bare_except_catches_system_exit_findings,
    discipline::exception_logged_and_reraised_findings,
    discipline::validation_error_mapped_to_500_findings,
    discipline::exception_silenced_in_finally_findings,
    discipline::exception_not_inheriting_base_findings,
    discipline::exception_for_control_flow_findings,
    discipline::error_message_embeds_sensitive_data_findings,
    discipline::retry_catches_broad_exception_findings,
    discipline::transaction_missing_rollback_findings,
    discipline::assert_for_validation_findings,
    discipline::warning_instead_of_exception_findings,
    discipline::exception_handler_no_logging_findings,
    discipline::deeply_nested_try_except_findings,
    discipline::suppress_with_base_exception_findings,
    discipline::oserror_without_errno_findings,
    discipline::custom_exception_string_code_findings,
    discipline::generator_close_without_finally_findings,
    discipline::overloaded_without_decorator_findings,
    discipline::protocol_isinstance_without_runtime_checkable_findings,
    discipline::optional_without_none_guard_findings,
    discipline::callable_without_param_types_findings,
    discipline::cast_without_narrowing_findings,
    discipline::type_alias_shadows_builtin_findings,
    discipline::namedtuple_where_dataclass_fits_findings,
    discipline::public_return_union_many_types_findings,
    discipline::typevar_without_bound_findings,
    discipline::generic_class_without_type_param_findings,
    discipline::protocol_method_lacks_annotations_findings,
    discipline::typed_dict_access_without_guard_findings,
    discipline::typed_dict_total_false_no_doc_findings,
    discipline::forward_ref_not_under_type_checking_findings,
    discipline::test_too_many_patches_findings,
    discipline::test_sleeps_for_coordination_findings,
    discipline::test_mutates_global_without_restore_findings,
    discipline::test_asserts_private_attribute_findings,
    discipline::test_datetime_without_freeze_findings,
    discipline::test_wraps_sut_in_try_except_findings,
    discipline::test_parametrize_single_case_findings,
    discipline::test_no_reason_skip_findings,
    discipline::test_float_equality_findings,
    discipline::test_loads_real_config_findings,
    discipline::test_makes_real_http_call_findings,
    discipline::test_coverage_multiple_scenarios_findings,
    discipline::integration_test_without_cleanup_findings,
    discipline::pytest_raises_no_match_findings,
    discipline::test_reimplements_production_logic_findings,
    discipline::test_imports_private_module_findings,
    discipline::mock_return_incompatible_type_findings,
    discipline::test_unittest_duplicated_setup_findings,
    discipline::test_depends_on_sibling_side_effects_findings,
];

pub(crate) const BOUNDARIES_EVALUATORS: &[FunctionEvaluator] = &[
    boundaries::sql_string_formatting_findings,
    boundaries::file_path_without_normalization_findings,
    boundaries::xml_external_entity_findings,
    boundaries::http_url_from_user_input_findings,
    boundaries::subprocess_shell_true_user_input_findings,
    boundaries::jinja2_autoescape_disabled_findings,
    boundaries::jwt_decode_none_algorithm_findings,
    boundaries::insecure_hash_for_security_findings,
    boundaries::pickle_from_external_source_findings,
    boundaries::debug_endpoint_without_env_guard_findings,
    boundaries::weak_random_for_security_token_findings,
    boundaries::open_redirect_findings,
    boundaries::arbitrary_file_write_user_path_findings,
    boundaries::cors_allow_all_no_guard_findings,
    boundaries::ssti_user_input_in_template_source_findings,
    boundaries::regex_catastrophic_backtracking_findings,
    boundaries::ldap_injection_findings,
    boundaries::state_changing_endpoint_missing_csrf_findings,
    boundaries::unbounded_list_accumulation_findings,
    boundaries::generator_consumed_twice_findings,
    boundaries::file_returned_without_close_path_findings,
    boundaries::weakref_without_live_check_findings,
    boundaries::lru_cache_on_instance_method_findings,
    boundaries::subprocess_pipe_without_communicate_findings,
    boundaries::socket_without_close_findings,
    boundaries::deepcopy_in_loop_findings,
    boundaries::redis_commands_in_loop_no_pipeline_findings,
    boundaries::tempfile_without_cleanup_findings,
    boundaries::db_pool_exceeds_server_max_findings,
    boundaries::closure_captures_large_object_findings,
    boundaries::heavyweight_object_in_tight_loop_findings,
    boundaries::pydantic_settings_allows_mutation_findings,
    boundaries::secrets_manager_per_call_findings,
    boundaries::toml_parsed_on_request_path_findings,
    boundaries::startup_log_includes_secret_findings,
    boundaries::pydantic_settings_no_forbid_extra_findings,
    boundaries::yaml_unsafe_loader_findings,
    boundaries::config_validated_lazily_findings,
    boundaries::sensitive_key_in_debug_log_dump_findings,
    boundaries::same_config_different_defaults_findings,
    boundaries::multiple_config_sources_no_precedence_findings,
    boundaries::pydantic_settings_no_prefix_findings,
];

pub(crate) const BOUNDARIES_FILE_EVALUATORS: &[FileEvaluator] = &[
    boundaries::hardcoded_secret_in_fixture_file_findings,
    boundaries::dotenv_load_dotenv_multi_file_findings,
    boundaries::feature_flag_scattered_findings,
];

pub(crate) const OBSERVABILITY_EVALUATORS: &[FunctionEvaluator] = &[
    observability::fstring_in_logging_findings,
    observability::logger_error_without_exc_info_findings,
    observability::trace_span_no_parent_context_findings,
    observability::health_check_queries_slow_table_findings,
    observability::exception_swallowed_before_sentry_findings,
    observability::hot_path_logs_without_sampling_findings,
    observability::otel_span_attaches_pii_findings,
    observability::structured_log_no_trace_id_findings,
    observability::log_in_signal_handler_findings,
    observability::alert_threshold_hardcoded_findings,
    observability::prometheus_metric_in_db_loop_findings,
    observability::observability_inconsistent_metric_names_findings,
    observability::star_import_in_production_findings,
    observability::importlib_in_request_handler_findings,
    observability::optional_import_on_hot_path_findings,
    observability::dynamic_plugin_no_allowlist_findings,
    observability::importlib_metadata_in_request_loop_findings,
    observability::pkg_resources_runtime_findings,
    observability::relative_import_crossing_sibling_findings,
    observability::sorted_to_extract_top_n_findings,
    observability::linear_membership_in_loop_findings,
    observability::manual_dict_increment_findings,
    observability::list_pop_zero_as_queue_findings,
    observability::zip_range_len_instead_of_enumerate_findings,
    observability::defaultdict_lambda_instead_of_builtin_findings,
    observability::filter_map_materialized_each_step_findings,
    observability::frozenset_not_used_for_constant_set_findings,
    observability::sorted_list_with_sort_instead_of_bisect_findings,
    observability::namedtuple_index_access_findings,
    observability::counter_most_common_all_for_top_one_findings,
    observability::repeated_key_hash_in_loop_findings,
    observability::chain_or_conditions_not_using_in_operator_findings,
    observability::ordered_dict_in_python37_plus_findings,
    observability::api_endpoint_no_response_schema_findings,
    observability::cursor_pagination_no_tiebreaker_findings,
    observability::bulk_endpoint_no_partial_failure_contract_findings,
    observability::rate_limit_no_retry_after_findings,
    observability::pydantic_validation_error_leaks_aliases_findings,
    observability::state_changing_endpoint_returns_200_empty_findings,
    observability::binary_response_no_content_type_findings,
    observability::large_response_fully_buffered_findings,
    observability::api_versioning_no_router_group_findings,
    observability::response_envelope_inconsistent_findings,
];

pub(crate) const OBSERVABILITY_FILE_EVALUATORS: &[FileEvaluator] = &[
    observability::logging_basic_config_library_file_findings,
    observability::logging_level_hardcoded_file_findings,
    observability::module_side_effect_file_findings,
    observability::test_helpers_in_production_file_findings,
    observability::init_reexports_private_file_findings,
    observability::public_package_missing_all_file_findings,
];
